Repository pereira-tech-talks/pereiratechtalks.com, pull requests merged in 2024-07, with the labels that each got.

#18 feat: post from 2019 to 2024
  src/assets/images/posts/banners/banner-2021.png
  src/assets/images/posts/banners/banner-2022.png
  src/assets/images/posts/banners/banner-2023.png
  src/assets/images/posts/banners/banner2019.jpeg
  src/assets/images/posts/banners/pereirajs.png
  src/assets/images/posts/banners/quarantine-tech-talks-2020.png
  src/content/post/eventos-en-2019.mdx
  src/content/post/eventos-en-2021.mdx
  src/content/post/eventos-en-2022.mdx
  src/content/post/noche-de-ia-y-chatgpt-tendencias-y-posibilidades.mdx
  src/content/post/pereirajs-se-une-a-pereira-tech-talks.mdx
  src/content/post/quarantine-tech-talks.mdx
Labels: enhancement

#19 Feat/migration
  src/assets/favicons/apple-touch-icon.png
  src/assets/favicons/favicon.ico
  src/assets/favicons/favicon.svg
  src/navigation.js
  src/pages/404.astro
  src/pages/about.astro
  src/pages/contact.astro
  src/pages/homes/mobile-app.astro
  src/pages/homes/personal.astro
  src/pages/homes/saas.astro
  src/pages/homes/startup.astro
  src/pages/index.astro
  src/pages/landing/click-through.astro
  src/pages/landing/lead-generation.astro
  src/pages/landing/pre-launch.astro
  src/pages/landing/product.astro
  src/pages/landing/sales.astro
  src/pages/landing/subscription.astro
  src/pages/pricing.astro
  src/pages/privacy.md
  src/pages/services.astro
  src/pages/terms.md
Labels: enhancement

#16 Adjust navbar and about view
  src/assets/images/about-bg.jpeg
  src/assets/images/hero-image.png
  src/assets/images/index-bg.jpg
  src/assets/images/logos/per-tech-talks-dark.svg
  src/assets/styles/Index.css
  src/components/Logo.astro
  src/components/widgets/Hero.astro
  src/pages/index.astro
Labels: enhancement

#21 #20 Add cache for Yarn
  .github/workflows/deploy.yml
  .github/workflows/pre-deploy.yml
Labels: enhancement

#27 Create method to get the upcoming events
  src/components/widgets/Announcement.astro
  src/content/event/next.mdx
  src/utils/event.ts
Labels: enhancement

#29 #20 Add cache for node_module and validate event data
  .github/workflows/pre-deploy.yml
  src/utils/event.ts
Labels: bug

#28 Create view to render events from Meetup
  .github/workflows/pre-deploy.yml
  .gitignore
  astro.config.mjs
  package.json
  src/assets/images/app-store.png
  src/assets/images/default.png
  src/assets/images/google-play.png
  src/assets/images/index-bg.jpg
  src/components/events/List.astro
  src/components/events/ListItem.astro
  src/components/events/Pagination.astro
  src/components/widgets/Announcement.astro
  src/layouts/PageLayout.astro
  src/navigation.js
  src/pages/meetups.astro
  src/types.d.ts
  src/utils/event.ts
  yarn.lock
Labels: enhancement

#46 Testing GH Actions
  README.md
Labels: Size - XS

#47 Solving deploy steup
  .github/workflows/deploy.yml
Labels: Size - XS

#51 Fixing deploy
  .github/workflows/deploy.yml
Labels: Size - XS

#53 Adjust styles and texts
  package.json
  src/assets/styles/Layout.css
  src/components/widgets/Header.astro
  src/layouts/Layout.astro
  src/navigation.js
  src/pages/[...blog]/[...page].astro
  src/pages/meetups.astro
  src/pages/pereira-tech-day.astro
Labels: Size - XS

#52 Updating workflows
  README.md
Labels: Size - XS

#54 Testing deploy
  README.md
Labels: Size - XS

#56 Feature deploy workflows
  .github/workflows/code_check.yml
  .github/workflows/deploy.yml
Labels: Size - S

#57 Testing deploy workflows
  README.md
Labels: Size - XS

#58 New workflows to deploy github actions
  .github/workflows/deploy.yml
  .github/workflows/release_and_publish.yml
  docker/local/pereiratechtalks/.env.example
  src/config.yaml
Labels: Size - M

#59 Feature deploy workflows
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#60 Feature deploy workflows
  .github/workflows/release_and_publish.yml
  package.json
Labels: Size - XS

#61 Feature deploy workflows
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#62 Feature deploy workflows
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#64 Feature deploy workflows
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#65 Feature deploy workflows
  .github/workflows/release_and_publish.yml
  text.txt
Labels: Size - XS

#66 Feature deploy workflows
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#67 Feature deploy workflows
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#68 Fixing markdown format
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#69 Feature deploy workflows
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#70 Feature deploy workflows
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#71 Feature deploy workflows
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#72 Feature deploy workflows
  .github/workflows/release_and_publish.yml
  package.json
Labels: Size - XS

#73 Feature deploy workflows
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#75 Feature deploy workflows
  .github/workflows/release_and_publish.yml
  .gitignore
  README.md
Labels: Size - M

#76 Feature deploy workflows
  README.md
  readme-banner.png
Labels: Size - XS

#77 Feature deploy workflows
  README.md
Labels: Size - XS

#78 Feature deploy workflows
  .github/workflows/release_and_publish.yml
  src/config.yaml
Labels: Size - XS

#74 feat :sparkles: schedule
  src/assets/images/people/karolina-landino.jpeg
  src/assets/images/people/vanessa-aristizabal.jpg
  src/components/widgets/Collaborators.astro
  src/components/widgets/Speakers.astro
  src/layouts/EventsLayout.astro
  src/pages/pereira-tech-day.astro
  src/types.d.ts
Labels: Size - M

#79 Create Code of Conduct
  astro.config.mjs
  src/pages/codigo-conducta.md
Labels: Size - M
