Repository pereira-tech-talks/pereiratechtalks.com, pull requests merged in 2024-08, with the labels that each got.

#80 Debug deploy
  README.md
Labels: Size - XS

#81 Fix landing bg banner
  src/assets/styles/Index.css
Labels: Size - XS

#82 Fix landing bg banner
  src/assets/images/index-bg-copy.jpg
  src/config.yaml
Labels: Size - XS

#83 Feat/adjust footer
  src/components/widgets/Footer.astro
  src/config.yaml
  src/navigation.js
  src/pages/pereira-tech-day.astro
Labels: Size - M

#84 Temporal fix to show the image intro
  src/config.yaml
Labels: Size - XS

#91 Replace permissions for pull_request_target
  .github/workflows/code_check.yml
  .github/workflows/pull_request_check.yml
Labels: Size - XS

#92 Correction in Melisa's LinkedIn info
  src/pages/pereira-tech-day.astro
Labels: Size - XS

#89 Debugging deployment workflows
  README.md
Labels: Size - XS

#93 Updating domain dns
  .github/workflows/pull_request_check.yml
  CNAME
  astro.config.mjs
  public/CNAME
Labels: Size - XS

#97 Debugging deployments
  .github/workflows/code_check.yml
  README.md
Labels: Size - XS

#98 Debug test deployments
  README.md
Labels: Size - XS

#99 Debugging github actions in the deployment action step
  README.md
Labels: Size - XS

#100 Debugging github actions in the deployment action step
  README.md
Labels: Size - XS

#101 Debugging github actions in the deployment action step
  README.md
Labels: Size - XS

#102 Debugging github actions in the deployment action step
  README.md
Labels: Size - XS

#105 Fix the url to see an individual event
  src/components/events/ListItem.astro
  src/pages/meetups.astro
Labels: Size - XS

#112 Upgrading packages
  package.json
  src/integration/utils/configBuilder.ts
  src/utils/blog.ts
  src/utils/images-optimization.ts
  src/utils/images.ts
Labels: Size - XS

#119 #113 Update event description
  src/navigation.js
  src/pages/pereira-tech-day.astro
Labels: Size - XS

#120 #115 Add email to contact for sponsors
  src/pages/pereira-tech-day.astro
Labels: Size - XS

#128 improve text description in the blog post card
  src/components/blog/GridItem.astro
Labels: Size - XS

#130 #124 Add action call in landing page
  src/pages/pereira-tech-day.astro
Labels: Size - XS, Pereira Tech Day

#129 Update codigo-conducta.md
  src/pages/codigo-conducta.md
Labels: Size - S

#131 #127 Add ASE UTP as gold sponsor
  src/assets/images/sponsors/ase-utp.png
  src/components/widgets/Brands.astro
  src/pages/pereira-tech-day.astro
Labels: Size - S, Pereira Tech Day

#132 #123 Add GitHub as gold sponsor
  src/assets/images/sponsors/github.png
  src/pages/pereira-tech-day.astro
Labels: Size - XS, Pereira Tech Day

#134 #123 Adjust component to render the image adter building
  src/assets/images/pereira-tech-day/sponsors/ase-utp.png
  src/assets/images/pereira-tech-day/sponsors/github.png
  src/components/widgets/Brands.astro
Labels: Size - XS, Pereira Tech Day

#135 Adjust GitHub Image Link for Statistics Tracking
  src/pages/pereira-tech-day.astro
Labels: Size - XS

#136 fix: :label: fix types on brands
  src/components/widgets/Brands.astro
  src/pages/pereira-tech-day.astro
  src/types.d.ts
Labels: Size - XS

#138 feat: :sparkles: new speakers section added
  src/assets/images/people/jose-alfredo-jaramillo.jpg
  src/components/widgets/Testimonials.astro
  src/pages/pereira-tech-day.astro
  src/types.d.ts
Labels: Size - S

#139 feat: :sparkles: update readme
  README.md
Labels: Size - XS

#140 feat: :sparkles: update new speaker
  src/assets/images/people/cesar-camacho.jpg
  src/pages/pereira-tech-day.astro
Labels: Size - XS

#143 feat: :sparkles: new page added
  src/navigation.js
  src/pages/lightning-talks.md
  src/pages/pereira-tech-day.astro
Labels: Size - XS

#144 Adjust redirections to sections
  src/navigation.js
  src/pages/pereira-tech-day/index.astro
  src/pages/pereira-tech-day/lightning-talks.md
Labels: Size - XS, Pereira Tech Day

#142 Update Vanessa Biography
  src/pages/pereira-tech-day/index.astro
Labels: Size - XS

#153 Upgrading npm packages
  package.json
Labels: Size - XS

#154 #150 Add location for PTD event
  src/components/widgets/Hero.astro
  src/pages/pereira-tech-day/index.astro
Labels: Size - XS, Pereira Tech Day

#156 Update pull_request_check.yml
  .github/workflows/pull_request_check.yml
Labels: Size - XS

#160 Social animations
  src/components/common/SocialShare.astro
Labels: Size - XS

#162 Updating blockchain post
  src/content/post/que-es-el-blockchain-y-como-esta-transformando-la-economia-y-la-industria.mdx
Labels: Size - XS

#163 Feature upgrading astro packages
  astro.config.mjs
  package.json
Labels: Size - XS

#166 #125 Update image and items
  src/assets/images/pereira-tech-day/about.jpg
  src/components/widgets/Content.astro
Labels: Size - XS, Pereira Tech Day

#167 #165 Add instructions to contribute
  CONTRIBUTING.md
  README.md
  src/navigation.js
  src/pages/about.astro
  src/pages/contributing.md
Labels: Size - M, Pereira Tech Day

#177 Add DailyBot as sponsor
  src/assets/images/pereira-tech-day/sponsors/dailybot.png
  src/content/post/302603058-pereira-tech-day.mdx
  src/pages/pereira-tech-day/index.astro
Labels: Size - XS, Pereira Tech Day

#181 Refresh events and get the next
  astro.config.mjs
  src/assets/images/posts/banners/highres_523057525.jpeg
  src/content/post/302972719-tech-soft-skills-ia.mdx
  src/utils/event.ts
Labels: Size - XS
