Repository pereira-tech-talks/pereiratechtalks.com, pull requests merged in 2024-12, with the labels that each got.

#236 Upgrading packages
  package-lock.json
  package.json
  src/assets/images/posts/banners/highres_524213596.jpeg
  src/assets/images/posts/banners/highres_524723445.jpeg
  src/assets/images/posts/banners/highres_524828335.jpeg
  src/content/post/304127870-ia-en-accin-aprende.mdx
  src/content/post/304596503-tecnologa-con-propsi.mdx
  src/content/post/304596568-de-la-utp-a-la-acade.mdx
Labels: Size - XL

#237 #230 Configure yag manager
  src/config.yaml
Labels: Size - XS

#239 #238 Update assets version 2024
  astro.config.mjs
  src/assets/favicons/apple-touch-icon.png
  src/assets/favicons/favicon.ico
  src/assets/favicons/favicon.svg
  src/assets/images/about-bg.jpeg
  src/assets/images/index-bg.jpg
  src/assets/images/logos/icon-black.webp
  src/assets/images/logos/icon.webp
  src/assets/images/logos/logo-black.webp
  src/assets/images/logos/logo.webp
  src/assets/images/logos/per-tech-talks-dark.svg
  src/assets/images/logos/per-tech-talks.png
  src/assets/images/logos/topbar-logo-black.webp
  src/assets/images/logos/topbar-logo.webp
  src/assets/images/team/pereiratechtalks-team-2018.jpg
  src/assets/images/team/pereiratechtalks-team-2024.jpg
  src/components/Logo.astro
  src/components/widgets/Footer.astro
  src/content/post/pereira-tech-talks-charlas-con-un-lenguaje-universal.mdx
  src/pages/about.astro
  src/pages/index.astro
Labels: Size - M

#240 #86 Update collaborators - Batch 1
  src/assets/images/people/team/alejo-rendon.jpg
  src/assets/images/people/team/andres-rodriguez.JPG
  src/assets/images/people/team/eliana-osorio.jpeg
  src/assets/images/people/team/hector-jimenez.jpg
  src/assets/images/people/team/jose-felipe-duarte.png
  src/assets/images/people/team/katherine-lopez.jpeg
  src/assets/images/people/team/luis-bazan.png
  src/assets/images/people/team/mega-barto.jpeg
  src/assets/images/people/team/melissa-escobar.png
  src/assets/images/people/team/santiago-bernal.jpeg
  src/assets/images/people/team/sergio-florez.png
  src/assets/images/people/team/stiven-cardona-monsalve.jpeg
  src/components/widgets/Collaborators.astro
  src/pages/about.astro
Labels: Size - S

#241 #155 Add Social&Co as sponsor
  src/navigation.js
Labels: Size - XS
