Repository pereira-tech-talks/pereiratechtalks.com, pull requests merged in 2024-10, with the labels that each got.

#217 📝 Add markdown standard document for Security Reports
  .github/pull_request_template.md
  .github/workflows/pull_request_check.yml
  SECURITY.md
Labels: Size - S, hacktoberfest

#219 Add collaborators
  src/assets/images/people/andres-rodriguez.JPG
  src/assets/images/people/cindy-jimenez.jpeg
  src/assets/images/people/eliana-osorio.jpeg
  src/assets/images/people/katherine-lopez.jpeg
  src/assets/images/people/leiver-campeon.jpg
  src/assets/images/people/lizeth-franco.jpeg
  src/assets/images/people/santiago-bernal.jpeg
  src/assets/images/posts/banners/highres_523607011.jpeg
  src/components/ui/ItemGrid2.astro
  src/components/widgets/Collaborators.astro
  src/content/post/302603058-pereira-tech-day.mdx
  src/content/post/303545199-machine-learning-aut.mdx
  src/pages/pereira-tech-day/index.astro
  src/utils/event.ts
Labels: Size - S

#220 Readme update
  README.md
Labels: Size - XS

#221 Removing character in the pull request template that is broken the re…
  .github/pull_request_template.md
Labels: Size - XS

#222 Feature testing deploy
  .github/pull_request_template.md
Labels: Size - XS

#223 🐛 Fix bug for eol of the pr
  .github/workflows/pull_request_check.yml
Labels: Size - XS, hacktoberfest

#228 Feature upgrading packages except svelte
  .github/dependabot.yml
  .gitignore
  package-lock.json
  package.json
Labels: Size - XXL

#231 #230: Update ID for GA4
  src/config.yaml
Labels: Size - XS

#232 Fixing merge conflict
  README.md
Labels: Size - XS

#235 Enable external scripts
  astro.config.mjs
Labels: Size - XS
